### ISSUE TITLE
Explicit dependency on maven-osgi-bundles 4.3 in 4.4 pom.xml

### ISSUE THREAD

**Issue by nickbattam** [ControlSystemStudio/cs-studio-thirdparty#23]
Our build of cs-studio-thirdparty has started failing since the 'master' version numbers were incremented from 4.3 to 4.4

There is an explicit dependency on the 4.3 version of maven-osgi-bundles in the pom:
<repository>
    <id>csstudio-maven-osgi-bundles</id>
    <url>${download.root}/maven-osgi-bundles/4.3</url>       
    <layout>p2</layout>
</repository>

Should this reference be updated?

**Comment by berryma4** [comment]
changed to use the cs-studio parameter in a new pull request
